// Code generated by SQLBoiler 4.4.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// Symbol is an object representing the database table.
type Symbol struct {
	ID        int         `boil:"id" json:"id" toml:"id" yaml:"id"`
	Name      null.String `boil:"name" json:"name,omitempty" toml:"name" yaml:"name,omitempty"`
	CreatedAt time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt time.Time   `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *symbolR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L symbolL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var SymbolColumns = struct {
	ID        string
	Name      string
	CreatedAt string
	UpdatedAt string
}{
	ID:        "id",
	Name:      "name",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

// Generated where

var SymbolWhere = struct {
	ID        whereHelperint
	Name      whereHelpernull_String
	CreatedAt whereHelpertime_Time
	UpdatedAt whereHelpertime_Time
}{
	ID:        whereHelperint{field: "`symbols`.`id`"},
	Name:      whereHelpernull_String{field: "`symbols`.`name`"},
	CreatedAt: whereHelpertime_Time{field: "`symbols`.`created_at`"},
	UpdatedAt: whereHelpertime_Time{field: "`symbols`.`updated_at`"},
}

// SymbolRels is where relationship names are stored.
var SymbolRels = struct {
}{}

// symbolR is where relationships are stored.
type symbolR struct {
}

// NewStruct creates a new relationship struct
func (*symbolR) NewStruct() *symbolR {
	return &symbolR{}
}

// symbolL is where Load methods for each relationship are stored.
type symbolL struct{}

var (
	symbolAllColumns            = []string{"id", "name", "created_at", "updated_at"}
	symbolColumnsWithoutDefault = []string{"name"}
	symbolColumnsWithDefault    = []string{"id", "created_at", "updated_at"}
	symbolPrimaryKeyColumns     = []string{"id"}
)

type (
	// SymbolSlice is an alias for a slice of pointers to Symbol.
	// This should generally be used opposed to []Symbol.
	SymbolSlice []*Symbol
	// SymbolHook is the signature for custom Symbol hook methods
	SymbolHook func(boil.Executor, *Symbol) error

	symbolQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	symbolType                 = reflect.TypeOf(&Symbol{})
	symbolMapping              = queries.MakeStructMapping(symbolType)
	symbolPrimaryKeyMapping, _ = queries.BindMapping(symbolType, symbolMapping, symbolPrimaryKeyColumns)
	symbolInsertCacheMut       sync.RWMutex
	symbolInsertCache          = make(map[string]insertCache)
	symbolUpdateCacheMut       sync.RWMutex
	symbolUpdateCache          = make(map[string]updateCache)
	symbolUpsertCacheMut       sync.RWMutex
	symbolUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var symbolBeforeInsertHooks []SymbolHook
var symbolBeforeUpdateHooks []SymbolHook
var symbolBeforeDeleteHooks []SymbolHook
var symbolBeforeUpsertHooks []SymbolHook

var symbolAfterInsertHooks []SymbolHook
var symbolAfterSelectHooks []SymbolHook
var symbolAfterUpdateHooks []SymbolHook
var symbolAfterDeleteHooks []SymbolHook
var symbolAfterUpsertHooks []SymbolHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Symbol) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range symbolBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Symbol) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range symbolBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Symbol) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range symbolBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Symbol) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range symbolBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Symbol) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range symbolAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Symbol) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range symbolAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Symbol) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range symbolAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Symbol) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range symbolAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Symbol) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range symbolAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddSymbolHook registers your hook function for all future operations.
func AddSymbolHook(hookPoint boil.HookPoint, symbolHook SymbolHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		symbolBeforeInsertHooks = append(symbolBeforeInsertHooks, symbolHook)
	case boil.BeforeUpdateHook:
		symbolBeforeUpdateHooks = append(symbolBeforeUpdateHooks, symbolHook)
	case boil.BeforeDeleteHook:
		symbolBeforeDeleteHooks = append(symbolBeforeDeleteHooks, symbolHook)
	case boil.BeforeUpsertHook:
		symbolBeforeUpsertHooks = append(symbolBeforeUpsertHooks, symbolHook)
	case boil.AfterInsertHook:
		symbolAfterInsertHooks = append(symbolAfterInsertHooks, symbolHook)
	case boil.AfterSelectHook:
		symbolAfterSelectHooks = append(symbolAfterSelectHooks, symbolHook)
	case boil.AfterUpdateHook:
		symbolAfterUpdateHooks = append(symbolAfterUpdateHooks, symbolHook)
	case boil.AfterDeleteHook:
		symbolAfterDeleteHooks = append(symbolAfterDeleteHooks, symbolHook)
	case boil.AfterUpsertHook:
		symbolAfterUpsertHooks = append(symbolAfterUpsertHooks, symbolHook)
	}
}

// One returns a single symbol record from the query.
func (q symbolQuery) One(exec boil.Executor) (*Symbol, error) {
	o := &Symbol{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(nil, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for symbols")
	}

	if err := o.doAfterSelectHooks(exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Symbol records from the query.
func (q symbolQuery) All(exec boil.Executor) (SymbolSlice, error) {
	var o []*Symbol

	err := q.Bind(nil, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Symbol slice")
	}

	if len(symbolAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Symbol records in the query.
func (q symbolQuery) Count(exec boil.Executor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count symbols rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q symbolQuery) Exists(exec boil.Executor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if symbols exists")
	}

	return count > 0, nil
}

// Symbols retrieves all the records using an executor.
func Symbols(mods ...qm.QueryMod) symbolQuery {
	mods = append(mods, qm.From("`symbols`"))
	return symbolQuery{NewQuery(mods...)}
}

// FindSymbol retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindSymbol(exec boil.Executor, iD int, selectCols ...string) (*Symbol, error) {
	symbolObj := &Symbol{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `symbols` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(nil, exec, symbolObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from symbols")
	}

	return symbolObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Symbol) Insert(exec boil.Executor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no symbols provided for insertion")
	}

	var err error
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.IsZero() {
		o.CreatedAt = currTime
	}
	if o.UpdatedAt.IsZero() {
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(symbolColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	symbolInsertCacheMut.RLock()
	cache, cached := symbolInsertCache[key]
	symbolInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			symbolAllColumns,
			symbolColumnsWithDefault,
			symbolColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(symbolType, symbolMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(symbolType, symbolMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `symbols` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `symbols` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `symbols` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, symbolPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}
	result, err := exec.Exec(cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into symbols")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == symbolMapping["id"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}
	err = exec.QueryRow(cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for symbols")
	}

CacheNoHooks:
	if !cached {
		symbolInsertCacheMut.Lock()
		symbolInsertCache[key] = cache
		symbolInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// Update uses an executor to update the Symbol.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Symbol) Update(exec boil.Executor, columns boil.Columns) (int64, error) {
	currTime := time.Now().In(boil.GetLocation())

	o.UpdatedAt = currTime

	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	symbolUpdateCacheMut.RLock()
	cache, cached := symbolUpdateCache[key]
	symbolUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			symbolAllColumns,
			symbolPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update symbols, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `symbols` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, symbolPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(symbolType, symbolMapping, append(wl, symbolPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	var result sql.Result
	result, err = exec.Exec(cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update symbols row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for symbols")
	}

	if !cached {
		symbolUpdateCacheMut.Lock()
		symbolUpdateCache[key] = cache
		symbolUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(exec)
}

// UpdateAll updates all rows with the specified column values.
func (q symbolQuery) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for symbols")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for symbols")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o SymbolSlice) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), symbolPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `symbols` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, symbolPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in symbol slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all symbol")
	}
	return rowsAff, nil
}

var mySQLSymbolUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Symbol) Upsert(exec boil.Executor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no symbols provided for upsert")
	}
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.IsZero() {
		o.CreatedAt = currTime
	}
	o.UpdatedAt = currTime

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(symbolColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLSymbolUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	symbolUpsertCacheMut.RLock()
	cache, cached := symbolUpsertCache[key]
	symbolUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			symbolAllColumns,
			symbolColumnsWithDefault,
			symbolColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			symbolAllColumns,
			symbolPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("models: unable to upsert symbols, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "`symbols`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `symbols` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(symbolType, symbolMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(symbolType, symbolMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}
	result, err := exec.Exec(cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for symbols")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == symbolMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(symbolType, symbolMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for symbols")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, nzUniqueCols...)
	}
	err = exec.QueryRow(cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for symbols")
	}

CacheNoHooks:
	if !cached {
		symbolUpsertCacheMut.Lock()
		symbolUpsertCache[key] = cache
		symbolUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// Delete deletes a single Symbol record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Symbol) Delete(exec boil.Executor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Symbol provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), symbolPrimaryKeyMapping)
	sql := "DELETE FROM `symbols` WHERE `id`=?"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from symbols")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for symbols")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q symbolQuery) DeleteAll(exec boil.Executor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no symbolQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from symbols")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for symbols")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o SymbolSlice) DeleteAll(exec boil.Executor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(symbolBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), symbolPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `symbols` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, symbolPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from symbol slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for symbols")
	}

	if len(symbolAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Symbol) Reload(exec boil.Executor) error {
	ret, err := FindSymbol(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *SymbolSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := SymbolSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), symbolPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `symbols`.* FROM `symbols` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, symbolPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(nil, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in SymbolSlice")
	}

	*o = slice

	return nil
}

// SymbolExists checks if the Symbol row exists.
func SymbolExists(exec boil.Executor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `symbols` where `id`=? limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, iD)
	}
	row := exec.QueryRow(sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if symbols exists")
	}

	return exists, nil
}
